name: Build Jarvis APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: stable

      # IMPORTANT STEP — generate android project
      - name: Create Flutter project structure
        run: |
          flutter create .

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release